version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    container_name: medscheduler-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: medscheduler
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: medscheduler-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: medscheduler
    ports:
      - "8080:8080"

volumes:
  db_data:
